#!/usr/bin/env bash
# This script installs nginx and get sure it listens to port 80

# Checks if NGINX exists and if not installs it.
if ! [ -x "$(command -v nginx)" ]
then
	apt-get update -y;
	apt-get upgrade -y;
	apt-get install -y nginx;
fi


# Checks if /etc/nginx/sites-enabled/default exists and updates it if so.
if [ -f /etc/nginx/sites-enabled/default ]; then
	sed -i '/listen [0-9]* default_server/c\\tlisten 80 default_server;' /etc/nginx/sites-enabled/default;
fi

# Checks if /var/www/html/index.nginx-debian.html exists and updates it if so.
if [ -f /var/www/html/index.nginx-debian.html ]; then
	sed -i 's/Welcome to nginx!/Holberton School/g' /var/www/html/index.nginx-debian.html;
fi
service nginx start;
