#!/usr/bin/env bash
# This script installs nginx and get sure it listens to port 80

# Checks if NGINX exists and if not installs it.
if ! [ -x "$(command -v nginx)" ]
then
	apt-get update -y;
	apt-get upgrade -y;
	apt-get install -y nginx;
fi


# Variables to handle redirection
redirection="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=q76bMs-NwRkhttps://www.youtube.com/watch?v=q76bMs-NwRk;\n\t}";

# Checks if /etc/nginx/sites-enabled/default exists and updates it if so.
if [ -f /etc/nginx/sites-enabled/default ]; then
	grep "listen 80 default_server" -q /etc/nginx/sites-enabled/default || sed -i '/listen [0-9]* default_server/c\\tlisten 80 default_server;' /etc/nginx/sites-enabled/default;
	grep "return 301" -q /etc/nginx/sites-enabled/default || sed -i "/server_name _;/a\ ${redirection}" /etc/nginx/sites-enabled/default;
fi

# Checks if /var/www/html/index.nginx-debian.html exists and updates it if so.
if [ -f /var/www/html/index.nginx-debian.html ]; then
	grep "Holberton School" -q  /var/www/html/index.nginx-debian.html || sed -i 's/Welcome to nginx!/Holberton School/g' /var/www/html/index.nginx-debian.html;
fi

# Start of nginx service
service nginx start;


