#!/bin/bash
# This script sets up a Load balancer to serve two web servers.

if ! [ -x "$(command -v haproxy)" ]
then
	apt-get update;
	apt-get install haproxy=1.6.\* -y;
fi

command_FE="\nfrontend main_frontend\n\tbind *:80\n\tdefault_backend main_backend";
command_BE="\nbackend main_backend\n\tbalance roundrobin\n\tserver web1 35.196.27.222:80 check\n\tserver web2 184.73.135.160:80 check";
grep "frontend main_frontend" -q /etc/haproxy/haproxy.cfg || echo -e "${command_FE}" >> /etc/haproxy/haproxy.cfg;
grep -e "^backend main_backend$" -q /etc/haproxy/haproxy.cfg || echo -e "${command_BE}" >> /etc/haproxy/haproxy.cfg;

service haproxy start;
service haproxy restart;
